name: CI

on: [push, pull_request, workflow_dispatch]

jobs:

  build:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v4


    - name: Debug Build
      run: |
        xcodebuild -project ./HP-ProBook-EliteBook.xcodeproj -alltargets -configuration Debug
        
    - name: Release Build
      run: |
        xcodebuild -project ./HP-ProBook-EliteBook.xcodeproj -alltargets -configuration Release
        
    - name: Allow executing
      run: |
        chmod 755 ./build/Release/HP-ProBook-EliteBook.app/Contents/MacOS/HP-ProBook-EliteBook
        chmod 755 ./build/Debug/HP-ProBook-EliteBook.app/Contents/MacOS/HP-ProBook-EliteBook
        Sleep 2
        
    - name: Upload to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HP-ProBook-EliteBook
        path: build/Release
        if-no-files-found: error
