name: CI

on: [push, pull_request, workflow_dispatch]

jobs:

  build:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v4


    - name: Debug Build
      run: |
        xcodebuild -alltargets -configuration Debug | xcpretty && exit ${PIPESTATUS[0]}

    - name: Release Build
      run: |
        xcodebuild -alltargets -configuration Release | xcpretty && exit ${PIPESTATUS[0]}

    - name: Upload to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HP-ProBook-EliteBook
        path: build/*/*.zip
        if-no-files-found: error
