name: CI

on: [push, pull_request, workflow_dispatch]

jobs:

  build:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v4

    - name: Release Build
      run: |
        xcodebuild -alltargets -configuration Release
        chmod +x ./build/Debug/HP-ProBook-EliteBook.app/Contents/MacOS/HP-ProBook-EliteBook
        
    - name: Upload to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HP-ProBook-EliteBook
        path: build/Release
        if-no-files-found: error
